### PR TITLE
FindHome, limits and Command_M fixes

### PR DESCRIPTION
**Pull request by MasterPIC**
FindHome seems to work by DeviceHub too.
As for Command_M I didn't check if the logic is to be reversed for S observers.

### CODE REVIEW

**Comment by charleslemaire0** [comment]
Move axis work as intended it is not a bug

**Comment by charleslemaire0** [comment]
of course no take look here:
https://ascom-standards.org/Help/Developer/html/M_ASCOM_DriverAccess_Telescope_MoveAxis.htm
I tested satellite tracking and it works :)

**Comment by MasterPIC** [comment]
https://ascom-standards.org/Help/Developer/html/M_ASCOM_DriverAccess_Telescope_CanMoveAxis.htm
As an example it's indicated "axisSecondary 1 Secondary axis (e.g., Declination or Altitude)"

If we assume Declination  as axisSecondary then a change of pier side should act as a change in mechanical axis too.

**Comment by charleslemaire0** [comment]
not at all... in ASCOM declination can be larger than 90° and smaller than -90°. when you send move axis+ then the value increase... it is a very bad design to consider all this pier stuff. I changed that compared to onstep, 4 years ago.

**Pull request merged**
