### PR TITLE
New feature for GEM mounts: tracking on for 6 hours after transit when far from Pole

### PR DESCRIPTION
**Pull request by MasterPIC**
This feature can be useful to keep tracking on after transit when pointing far from Pole: no tripod collision can typically occur.
Minimum distance from Pole (in degrees) to override the safety tracking lock is user defined.
By default this features is disabled.

French and German translations are missing.
For Southern observers I didn't check if checkMeridian logic is to be adapted.

### CODE REVIEW

**Comment by charleslemaire0** [comment]
could you more explain it is not clear what is the benefit

**Comment by MasterPIC** [comment]
The user can actually disable meridian limits and rely on software to have no tripod collisions.
Or he can prefer to have safety tracking lock (i.e. meridian limits) enabled.
But enabling meridian limits can be too restrictive when pointing far from Pole.
Mainly for imaging I see the possibility to avoid a flip or to postpone it more than 5 minutes after transit time when far from Pole. With the old FS2 I was used to keep going on and make a flip only if strictly required...
While imaging by long exposure times (e.g. 20min) and near local meridian there is the necessity to stop imaging, wait for several minutes to be able to make a flip and then go on...
The user could start imaging from the beginning from the "wrong side" to have no issues at all, but it's not allowed by GoTo.
This is the main reason why I prefer to postpone a flip, if feasible. A re-centring command, several minutes after transit, wouldn't cause any issue.
The only risk, with unattended use, is a possible tripod collision if the first GoTo after transit occurs several hours later. We could add for this scenario a slewing only on Ra to exit from this condition.
But keeping the feature I'm suggesting disabled by default is enough according to me.

**Comment by charleslemaire0** [comment]
Hi Armando,

If you have overlapping méridian limit it is possible to sélect the side. I
will explain on the group how to do that

Thanks for the clear description

Charles

**Comment by MasterPIC** [comment]
Hi Charles,
I may be wrong but if I set overlapping meridian limits I can have tripod collisions when not far from Pole.

**Comment by charleslemaire0** [comment]
The user could start imaging from the beginning from the "wrong side" to have no issues at all, but it's not allowed by GoTo.
it is possible : in teenastro there is an LX200 command to set the destination side of pier before the goto, the problem is that ASCOM doesn't support this natively. so yo have to do it in your script, by sending an ASCOM string command.

when you are in the overlapping you can flip with the set destination of pier command. Normally with +- 1 hour overlap there is no more problem with astrophotography.
you can also set more limit to the West and less to the East for example (0,+2) then if your are close to the meridian on the west side you can send a flip command and the scope will automatically flip to the East side.

Charles

**Comment by MasterPIC** [comment]
The feature I'm suggesting offers the ability to postpone a flip without any kind of user intervention when pointing far from pole. If the user doesn't like this feature he can keep it disabled.
While imaging several automated steps can be triggered. And injecting what you're suggesting in a sequence is overcomplicated.
The main aim for an astroimager is using the time at its best. My idea can help and simplifies the management of the mount.

**Comment by MasterPIC** [comment]
The overlapping you're referring to doesn't take into account declination. So a change of pier side can cause a collision.
If you think the user should be warned about the risks of the feature I'm suggesting then we can add a warning message.

**Comment by charleslemaire0** [comment]
I heard from other project mount project people that would like a merdian limit that depends on the declination. ok it is  a bit different but in the same topic.
There are plenty people using TeenAstro and I am not willing to implement thing that can cause trouble.
I could add a meridian limit for several interval of the declination. for example close to the pole and a normal value.
I could do that later, we have to enlarge the eeprom values

but the problem with the flip management is not resolved and is aclient software issue not the mount.
Teenastro can exactly do what you want stay on the right side for a goto or flip if it is possible

**Comment by charleslemaire0** [comment]
actually the transformation pipeline is for me much more important because at the moment the value RA value are not changing when the telescop is excactly at the pole

**Comment by MasterPIC** [comment]
For N.I.N.A. there is a plug-in that allows to set several intervals and limits. But obviously relying on the firmware is preferable.
My idea was to keep limits enabled when strictly required and keep them disabled (just for tracking, not GoTo) to be able to acquire signal when the target is higher.

**Comment by MasterPIC** [comment]
What about adding a define to include it and keep it hidden?
Only the users that compile firmware by themself will find it. Dummy users troubles solved...

**Comment by charleslemaire0** [comment]
Why not?! then you can continue to contribute

**Comment by MasterPIC** [comment]
They don't take into account declination...

**Comment by MasterPIC** [comment]
Just updated by commit https://github.com/charleslemaire0/TeenAstro/pull/58/commits/70aeb5431b10e9aaaba0c466a88e48b0d8f923f5

Please let me know if you think it's ok.

**Comment by MasterPIC** [comment]
I'm not sure where to define UNOFFICIALFEATURES.

**Comment by charleslemaire0** [comment]
could you resolve the conflict?

**Comment by MasterPIC** [comment]
Please check it. I modified just the involved file on my fork to adapt it to your fork without any sync to your fork.
A merge before further changes would be appreciated...

**Pull request merged**
